import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "/node_modules/bootstrap/dist/css/bootstrap.min.css";
import "/node_modules/@icon/icofont/icofont.css";
import Header from "@/components/common/Header/Header";
import BootstrapClient from "@/components/BootstrapClient";
import Footer from "@/components/common/Footer/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ScrollToTopBtn from "@/components/common/ScrollToTopBtn/ScrollToTopBtn";
import { SessionProvider } from "next-auth/react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <SessionProvider>
            <Header />
            <ScrollToTopBtn />
            {children}
            <Footer />
            <BootstrapClient />
          </SessionProvider>
        <ToastContainer
          position="bottom-right"
          autoClose={3500}
          theme="colored"
        />
      </body>
    </html>
  );
}
